### Requisação para a raiz da aplicação
GET http://localhost:5020

### Listar arqueologos
GET http://localhost:5020/arqueologo/listar

### Listar artefatos
GET http://localhost:5020/artefato/listar

### Listar fosseis
GET http://localhost:5020/fossil/listar

### Listar paleontologos
GET http://localhost:5020/paleontologo/listar

### Buscar arqueologos
GET http://localhost:5020/arqueologo/buscar/{nome}

### Buscar artefatos
GET http://localhost:5020/artefato/buscar/{nome}

### Buscar fosseis
GET http://localhost:5020/fossil/buscar/{nome}

### Buscar peleontologos
GET http://localhost:5020/peleontologo/buscar/{nome}

### Cadastrar artefato
POST http://localhost:5020/artefato/cadastrar
Content-Type: application/json

{
  "nome": "Bastão de marfim",
  "periodo": "Paleolítico Superior",
  "civilizacaoOrigem": "Primeiros humanos America do Norte",
  "funcionalidade": "Criação de cordas",
  "dimensao": "21cm",
  "material": "Origem vegetal"
}

### Cadastrar fossil
POST http://localhost:5020/fossil/cadastrar
Content-Type: application/json

{
  "nome": "Maximus",
  "nomeCientifico": "Tyrannosaurus rex",
  "localizacaoDescoberta": "Ilha de Madagascar",
  "tipoFossil": "Crânio",
  "especiaOrganismo": "T-Rex",
  "condicaoPreservacao": "Deteriorada",
  "epocaGeologica": "Cretáceo"
}

### Cadastrar paleontologo
POST http://localhost:5020/paleontologo/cadastrar
Content-Type: application/json

{
  "nome": "Jose Luiz Datena",
  "cpf": "123-123-643.00",
  "dataNascimento": "05/09/1995",
  "anosExperiencia": "4",
  "areaEspecializacaoId": 1,
  "idMatricula":578234634734
}

### Cadastrar arqueologo
POST http://localhost:5020/arqueologo/cadastrar
Content-Type: application/json

{
  "nome": "Tiririca Messias Bolsonaro",
  "cpf": "772-642-126.12",
  "dataNascimento": "10/01/1980",
  "anosExperiencia": "10",
  "idRegistroProfissional":45745743456674,
  "formacaoAcademicaId": 2
}

### Deletar fossil
DELETE http://localhost:5020/fossil/deletar/{id}

### Deletar artefato
DELETE http://localhost:5020/artefato/deletar/{id}

### Deletar arqueologo
DELETE http://localhost:5020/arqueologo/deletar/{id}

### Deletar paleontologo
DELETE http://localhost:5020/paleontologo/deletar/{id}

### Alterar fossil
PUT http://localhost:5020/fossil/alterar/{id}
Content-Type: application/json

{
  "nome": "Horridus"
}

### Alterar artefato
PUT http://localhost:5020/artefato/alterar/{id}
Content-Type: application/json

{
  "periodo": "Cenozoico"
}

### Alterar arqueologo
PUT http://localhost:5020/arqueologo/alterar/{id}
Content-Type: application/json

{
  "AnosExperiencia": 7
}

### Alterar paleontologo
PUT http://localhost:5020/paleontologo/alterar/{id}
Content-Type: application/json

{
  "idMatricula": "666364534-356-432"
}